parameters:
services:
  _defaults:
    autowire: false
    autoconfigure: true

  Yosimitso\WorkingForumBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Yosimitso\WorkingForumBundle\Controller\BaseController:
    calls:
      - ["setParameters",["@doctrine.orm.entity_manager","@yosimitso_workingforum.security.authorization","@=service('security.token_storage').getToken().getUser()","@session", "@translator", "@knp_paginator", '@yosimitso_workingforum.service.bundle_parameters']]
      - { method: setContainer, arguments: [ '@service_container' ] }


  Yosimitso\WorkingForumBundle\Controller\ForumController:
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true
    arguments:
      - '%yosimitso_working_forum.date_format%'
      - '%yosimitso_working_forum.post_per_page%'
      - '%yosimitso_working_forum.thread_per_page%'
    calls:
      - { method: setContainer, arguments: [ '@service_container' ] }

  Yosimitso\WorkingForumBundle\Controller\ThreadController:
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true
    arguments:
      - "@yosimitso_workingforum.service.fileuploader"
      - "@yosimitso_workingforum.extension.smiley"
      - "@yosimitso_workingforum.service.thread"

  Yosimitso\WorkingForumBundle\Controller\Admin\AdminController:
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true

  Yosimitso\WorkingForumBundle\Controller\Admin\AdminForumController:
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true

  Yosimitso\WorkingForumBundle\Controller\Admin\AdminReportController:
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true

  Yosimitso\WorkingForumBundle\Controller\Admin\AdminRulesController:
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true
    arguments:
      - "@yosimitso_workingforum.extension.smiley"

  yosimitso_workingforum.controller.admin_users:
    class: Yosimitso\WorkingForumBundle\Controller\Admin\AdminUsersController
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true

  yosimitso_workingforum.controller.search:
    class: Yosimitso\WorkingForumBundle\Controller\SearchController
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true
    arguments:
      - "@form.factory"

  yosimitso_workingforum.controller.post:
    class: Yosimitso\WorkingForumBundle\Controller\PostController
    parent: Yosimitso\WorkingForumBundle\Controller\BaseController
    public: true
    arguments:
      - "@yosimitso_workingforum.service.thread"

  yosimitso_workingforum.extension.smiley:
    class: Yosimitso\WorkingForumBundle\Twig\Extension\SmileyTwigExtension
    tags:
      - { name: twig.extension }
    arguments: ["@request_stack", "@assets.packages"]

  yosimitso_workingforum.extension.quote:
    class: Yosimitso\WorkingForumBundle\Twig\Extension\QuoteTwigExtension
    tags:
      - { name: twig.extension }
    arguments: ["@doctrine.orm.entity_manager", '@translator']

  yosimitso_workingforum.extension.config:
    class: Yosimitso\WorkingForumBundle\Twig\Extension\ConfigurationTwigExtension
    tags:
      - { name: twig.extension }
    arguments: ["%yosimitso_working_forum.theme_color%"]

  yosimitso_workingforum.security.authorization:
    class: Yosimitso\WorkingForumBundle\Security\AuthorizationGuard
    arguments:
      - "@security.authorization_checker"
      - "@security.token_storage"
      - "%yosimitso_working_forum.allow_anonymous_read%"

  yosimitso_workingforum.service.fileuploader:
    class: Yosimitso\WorkingForumBundle\Service\FileUploaderService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%yosimitso_working_forum.file_upload%"
      - "@translator"

  yosimitso_workingforum.service.subscription:
    class: Yosimitso\WorkingForumBundle\Service\SubscriptionService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@mailer"
      - "@translator"
      - "%yosimitso_working_forum.site_title%"
      - "@twig"
      -  "@=container.hasParameter('swiftmailer.sender_address') ? parameter('swiftmailer.sender_address') : null"

  yosimitso_workingforum.listener.post:
    class: Yosimitso\WorkingForumBundle\Event\PostEvent
    arguments:
      - "%yosimitso_working_forum.post_flood_sec%"
      - "@translator"
      - "@yosimitso_workingforum.service.subscription"
      - "%yosimitso_working_forum.thread_subscription%"
    tags:
      - { name: doctrine.event_listener, event: prePersist}
      - { name: doctrine.event_listener, event: postPersist}


  yosimitso_workingforum.service.thread:
    class: Yosimitso\WorkingForumBundle\Service\ThreadService
    arguments:
      - "%yosimitso_working_forum.lock_thread_older_than%"
      - "@knp_paginator"
      - "%yosimitso_working_forum.post_per_page%"
      - "@request_stack"
      - "@doctrine.orm.entity_manager"
      - "@security.token_storage"
      - "@yosimitso_workingforum.service.fileuploader"
      - "@yosimitso_workingforum.security.authorization"
      - "@yosimitso_workingforum.service.bundle_parameters"
      - "@form.factory"
      - "@router"
      - "@twig"

  yosimitso_workingforum.service.bundle_parameters:
    class: Yosimitso\WorkingForumBundle\Service\BundleParametersService
    arguments:
      - "@service_container"

  yosimitso_workingforum.param_converters.forum:
    class: Yosimitso\WorkingForumBundle\ParamConverter\GenericParamConverter
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@yosimitso_workingforum.security.authorization'
      - 'Yosimitso\WorkingForumBundle\Entity\Forum'
    tags:
      - { name: request.param_converter, priority: 20 }

  yosimitso_workingforum.param_converters.subforum:
    class: Yosimitso\WorkingForumBundle\ParamConverter\GenericParamConverter
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@yosimitso_workingforum.security.authorization'
      - 'Yosimitso\WorkingForumBundle\Entity\Subforum'
    tags:
      - { name: request.param_converter, priority: 20 }

  yosimitso_workingforum.param_converters.thread:
    class: Yosimitso\WorkingForumBundle\ParamConverter\GenericParamConverter
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@yosimitso_workingforum.security.authorization'
      - 'Yosimitso\WorkingForumBundle\Entity\Thread'
    tags:
      - { name: request.param_converter, priority: 20 }

  yosimitso_workingforum.param_converters.post:
    class: Yosimitso\WorkingForumBundle\ParamConverter\GenericParamConverter
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@yosimitso_workingforum.security.authorization'
      - 'Yosimitso\WorkingForumBundle\Entity\Post'
    tags:
      - { name: request.param_converter, priority: 20 }